# pagerduty Exporter Workflow
# This workflow responsible for running pagerduty exporter.
# integration.secrets.token: PagerDuty API token
# integration.config.api_url: Pagerduty api url. If not specified, the default will be https://api.pagerduty.com

on:
    workflow_dispatch:
    schedule:
        - cron: '0 */1 * * *' # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Run pagerduty Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: pagerduty
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
				        port_base_url: "https://api.getport.io"
                config: |
                    token: ${{ secrets.token }}
                    api_url: https://api.pagerduty.com
